### ISSUE TITLE
ESP32 GPIO allocation

### ISSUE THREAD

**Issue by davefes** [notUnique/DS3231micro#2]
Thank you for providing this library. 

I can get it to work using pins 5 and 4 as per your example.

However, if I try using other pins, ie 19 and 18 and using the SoftI2C Micropython class I get:
```py
  File "DS3231micro.py", line 66, in getSeconds
OSError: [Errno 19] ENODEV
```
Could you suggest a fix, just in case I do need to move to other pins?

**Comment by peterhinch** [comment]
Try adding pullup resistors. The chip's internal pullups are not strong enough for reliable I2C.

**Comment by davefes** [comment]
The schematic supplied shows 10K pull-ups but the resistors on the boards are actually used for other purposes!!  Thank you for the prompt.
