### ISSUE TITLE
The day of week field is from 1-7, 1 is Monday or Sunday?

### ISSUE THREAD

**Issue by paulovitorbal** [notUnique/DS3231micro#4]
It is not clear to me how the `day of week` field works.

**Comment by notUnique** [comment]
Sry, better late than never right...

Well I'm used to weeks starting on Monday. If you take a look in the examples I wrote, you can see I set the time to 1 as day of week and wrote in the comment that this represents Monday.

```
# set time to 2019, November, 23, Monday, 19 h, 50 min, 0 sec
rtc.setDateTime(19, 11, 23, 1, 19, 50, 0)
```
